import type { Student } from "@/types/students.types";

// Stand-in for useGetStudentsQuery() / useGetAttendanceQuery() until the
// studentsApi + attendanceApi slices are wired up.
export const mockStudents: Student[] = [
  {
    id: "1",
    sr: 1,
    name: "Maya Lin",
    email: "maya.lin@edu.org",
    initials: "ML",
    avatarColor: "bg-blue-100 text-blue-600",
    rollNumber: "STU-2024-0891",
    program: "BSCS",
    guardianName: "David Lin",
    contactNumber: "+1 (555) 234-8901",
    dateJoined: "Aug 15, 2024",
    attendanceDate: "Oct 24, 2024",
    arrivalTime: "08:05 AM",
    status: "Present",
    attendanceRate: 96,
  },
  {
    id: "2",
    sr: 2,
    name: "Noah Patel",
    email: "noah.p@edu.org",
    initials: "NP",
    avatarColor: "bg-indigo-100 text-indigo-600",
    rollNumber: "STU-2024-0742",
    program: "BSIT",
    guardianName: "Pooja Patel",
    contactNumber: "+1 (555) 872-4419",
    dateJoined: "Sep 01, 2024",
    attendanceDate: "Oct 24, 2024",
    arrivalTime: "08:14 AM",
    status: "Present",
    attendanceRate: 91,
  },
  {
    id: "3",
    sr: 3,
    name: "Chloe Davis",
    email: "chloe.d@edu.org",
    initials: "CD",
    avatarColor: "bg-rose-100 text-rose-600",
    rollNumber: "STU-2024-1102",
    program: "BSSE",
    guardianName: "Robert Davis",
    contactNumber: "+1 (555) 412-9023",
    dateJoined: "Aug 20, 2024",
    attendanceDate: "Oct 24, 2024",
    arrivalTime: "08:42 AM",
    status: "Late",
    attendanceRate: 68,
  },
  {
    id: "4",
    sr: 4,
    name: "Alex Rivera",
    email: "alex.r@edu.org",
    initials: "AR",
    avatarColor: "bg-slate-100 text-slate-600",
    rollNumber: "STU-2024-0450",
    program: "BS Zoology",
    guardianName: "Elena Rivera",
    contactNumber: "+1 (555) 609-3382",
    dateJoined: "Aug 18, 2024",
    attendanceDate: "Oct 24, 2024",
    arrivalTime: "08:02 AM",
    status: "Present",
    attendanceRate: 98,
  },
  {
    id: "5",
    sr: 5,
    name: "Emma Watson",
    email: "emma.w@edu.org",
    initials: "EW",
    avatarColor: "bg-red-100 text-red-600",
    rollNumber: "STU-2024-0988",
    program: "BSDS",
    guardianName: "Thomas Watson",
    contactNumber: "+1 (555) 781-9920",
    dateJoined: "Sep 05, 2024",
    attendanceDate: "Oct 24, 2024",
    arrivalTime: null,
    status: "Absent",
    attendanceRate: 22,
  },
  {
    id: "6",
    sr: 6,
    name: "Jayden Brooks",
    email: "j.brooks@edu.org",
    initials: "JB",
    avatarColor: "bg-blue-100 text-blue-600",
    rollNumber: "STU-2024-0312",
    program: "BS Biotechnology",
    guardianName: "Marcus Brooks",
    contactNumber: "+1 (555) 914-5501",
    dateJoined: "Sep 01, 2024",
    attendanceDate: "Oct 24, 2024",
    arrivalTime: "08:08 AM",
    status: "Present",
    attendanceRate: 94,
  },
  {
    id: "7",
    sr: 7,
    name: "Sofia Rossi",
    email: "sofia.r@edu.org",
    initials: "SR",
    avatarColor: "bg-emerald-100 text-emerald-600",
    rollNumber: "STU-2024-0815",
    program: "BSCS",
    guardianName: "Giulia Rossi",
    contactNumber: "+1 (555) 349-1129",
    dateJoined: "Aug 15, 2024",
    attendanceDate: "Oct 24, 2024",
    arrivalTime: "08:00 AM",
    status: "Present",
    attendanceRate: 99,
  },
  {
    id: "8",
    sr: 8,
    name: "Ethan Kim",
    email: "ethan.k@edu.org",
    initials: "EK",
    avatarColor: "bg-sky-100 text-sky-600",
    rollNumber: "STU-2024-0677",
    program: "BSIT",
    guardianName: "Min-Jun Kim",
    contactNumber: "+1 (555) 762-0941",
    dateJoined: "Sep 01, 2024",
    attendanceDate: "Oct 24, 2024",
    arrivalTime: "08:25 AM",
    status: "Present",
    attendanceRate: 90,
  },
];

export const studentsSummary = {
  total: 1240,
  presentPct: 92.4,
  latePct: 3.8,
  absentPct: 3.8,
};
