import { useEffect, useState } from "react";
import { CalendarDays, Mail, Phone, UserRound, X } from "lucide-react";

export interface DialogField {
  name: string;
  label: string;
  placeholder?: string;
  type?: "text" | "email" | "tel" | "date" | "number" | "select" | "textarea";
  required?: boolean;
  options?: string[];
  autoGenerated?: boolean;
}

interface RecordDialogProps {
  open: boolean;
  entity: string;
  initialValues?: Record<string, string | number | boolean>;
  fields: DialogField[];
  onClose: () => void;
  onSave: (values: Record<string, string>) => void;
}

const EMPTY_VALUES: Record<string, string | number | boolean> = {};

export default function RecordDialog({ open, entity, initialValues = EMPTY_VALUES, fields, onClose, onSave }: RecordDialogProps) {
  const [values, setValues] = useState<Record<string, string>>({});
  useEffect(() => {
    if (open) setValues(Object.fromEntries(fields.map((field) => [field.name, String(initialValues[field.name] ?? "")] )));
  }, [open, initialValues, fields]);
  if (!open) return null;
  const editing = Object.keys(initialValues).length > 0;

  function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    onSave(values);
  }

  const iconFor = (field: DialogField) => field.type === "email" ? Mail : field.type === "tel" ? Phone : field.type === "date" ? CalendarDays : UserRound;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/45 p-4 backdrop-blur-sm" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}>
      <section role="dialog" aria-modal="true" aria-labelledby="record-dialog-title" className="max-h-[90vh] w-full max-w-[540px] overflow-hidden rounded-xl border border-slate-200 bg-white shadow-2xl">
        <header className="flex items-start justify-between border-b border-slate-100 px-5 py-4">
          <div><h2 id="record-dialog-title" className="text-base font-semibold text-slate-800">{editing ? `Edit ${entity}` : `Add New ${entity}`}</h2><p className="mt-1 text-xs text-slate-500">{editing ? `Update the ${entity.toLowerCase()} details below.` : `Enter the ${entity.toLowerCase()} details below.`}</p></div>
          <button type="button" onClick={onClose} aria-label="Close dialog" className="rounded-md p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-700"><X className="h-4 w-4" /></button>
        </header>
        <form onSubmit={submit} className="flex max-h-[calc(90vh-76px)] flex-col">
          <div className="grid gap-x-3 gap-y-3 overflow-y-auto p-5 sm:grid-cols-2">
            {fields.map((field) => {
              const Icon = iconFor(field);
              const value = values[field.name] ?? "";
              return <label key={field.name} className={`block min-w-0 ${field.type === "textarea" ? "sm:col-span-2" : ""}`}>
                <span className="mb-1.5 block text-[11px] font-medium text-slate-700">{field.label}{field.required && <span className="ml-0.5 text-rose-500">*</span>}</span>
                <span className="relative block">
                  {field.type === "select" ? <select required={field.required} value={value} onChange={(event) => setValues((prev) => ({ ...prev, [field.name]: event.target.value }))} className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs text-slate-700 outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100"><option value="">Select {field.label.toLowerCase()}</option>{field.options?.map((option) => <option key={option} value={option}>{option}</option>)}</select>
                    : field.type === "textarea" ? <textarea required={field.required} value={value} placeholder={field.placeholder} onChange={(event) => setValues((prev) => ({ ...prev, [field.name]: event.target.value }))} rows={2} className="w-full resize-y rounded-lg border border-slate-200 px-3 py-2 text-xs outline-none placeholder:text-slate-400 focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100" />
                    : <><Icon className="pointer-events-none absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-slate-400" /><input type={field.type ?? "text"} required={field.required} readOnly={field.autoGenerated && !editing} value={value} placeholder={field.placeholder} min={field.type === "number" ? 0 : undefined} onChange={(event) => setValues((prev) => ({ ...prev, [field.name]: event.target.value }))} className={`w-full rounded-lg border border-slate-200 py-2 pl-8 pr-3 text-xs outline-none placeholder:text-slate-400 focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100 ${field.autoGenerated && !editing ? "bg-slate-50 text-slate-500" : "bg-white"}`} /></>}
                </span>
              </label>;
            })}
          </div>
          <footer className="flex shrink-0 justify-end gap-2 border-t border-slate-100 px-5 py-3">
            <button type="button" onClick={onClose} className="rounded-lg border border-slate-200 px-3.5 py-2 text-xs font-medium text-slate-600 hover:bg-slate-50">Cancel</button>
            <button type="submit" className="rounded-lg bg-indigo-600 px-3.5 py-2 text-xs font-medium text-white hover:bg-indigo-700">{editing ? `Save ${entity}` : `Add ${entity}`}</button>
          </footer>
        </form>
      </section>
    </div>
  );
}
